### Create get or create profile
# Warning: before running all other endpoints, you absolutely need to call this endpoint.
# It'll create the user in the database which is needed by other endpoints.
# @name profile
GET http://localhost:4000/user/profile?email=test@example.com HTTP/1.1
content-type: application/json

### Not found page
GET http://localhost:4000/not-found HTTP/1.1
content-type: application/json

### Create new team
POST http://localhost:4000/team/create HTTP/1.1
content-type: application/json

{
  "userEmail": "test@example.com",
  "displayName": "team 1010"
}

### Delete team
@teamId = {{profile.response.body.$.teamList[0].id}}
DELETE http://localhost:4000/team/{{teamId}} HTTP/1.1
content-type: application/json

### Change team name
@teamId = {{profile.response.body.$.teamList[0].id}}
PUT http://localhost:4000/team/{{teamId}}/name HTTP/1.1
content-type: application/json

{
  "displayName": "team one"
}

### List members in team
@teamId = {{profile.response.body.$.teamList[0].id}}
GET http://localhost:4000/team/{{teamId}}/list-members HTTP/1.1

### Create Todo
# @name todoCreation
@teamId = {{profile.response.body.$.teamList[0].id}}
POST http://localhost:4000/{{teamId}}/todo/create HTTP/1.1
content-type: application/json

{
  "title": "new Hello world"
}

### Get Todo
@id = {{todoCreation.response.body.$.id}}
@teamId = {{profile.response.body.$.teamList[0].id}}
GET http://localhost:4000/{{teamId}}/todo/{{id}} HTTP/1.1

### Update Todo
@id = {{todoCreation.response.body.$.id}}
@teamId = {{profile.response.body.$.teamList[0].id}}
PUT http://localhost:4000/{{teamId}}/todo/{{id}} HTTP/1.1
content-type: application/json

{
  "title": "Hello world 1000"
}

### Delete Todo
@id = {{todoCreation.response.body.$.id}}
@teamId = {{profile.response.body.$.teamList[0].id}}
DELETE http://localhost:4000/{{teamId}}/todo/{{id}} HTTP/1.1

### List Todo
@teamId = {{profile.response.body.$.teamList[0].id}}
GET http://localhost:4000/{{teamId}}/todo/list HTTP/1.1

### Get settings
@teamId = {{profile.response.body.$.teamList[0].id}}
GET http://localhost:4000/team/{{teamId}}/settings HTTP/1.1
content-type: application/json

### Stripe create session
# Please update the priceId value with your own value
@teamId = {{profile.response.body.$.teamList[0].id}}
POST http://localhost:4000/{{teamId}}/billing/create-checkout-session HTTP/1.1
content-type: application/json

{
  "priceId": "price_1M4pljARauCrL6c2Kwj45IYx"
}

### Create Stripe customer portal link
@teamId = {{profile.response.body.$.teamList[0].id}}
POST http://localhost:4000/{{teamId}}/billing/customer-portal HTTP/1.1
content-type: application/json

### Update user email
PUT http://localhost:4000/user/email-update HTTP/1.1
content-type: application/json

{
  "email": "test@gmail.com"
}

### Team invite
# It'll send an email to the address email and in local/dev environement,
# you can open your browser at http://localhost:8005 and visualize the email.
@teamId = {{profile.response.body.$.teamList[0].id}}
POST http://localhost:4000/team/{{teamId}}/invite HTTP/1.1
content-type: application/json

{
  "email": "test3@gmail.com",
  "role": "ADMIN"
}

### Get Join info
# Please update the verification code, the code is generated by `/team/{teamId}/invite`.
# Go to http://localhost:8005 and you'll able to see all the emails sent from the backend.
@teamId = {{profile.response.body.$.teamList[0].id}}
GET http://localhost:4000/team/{{teamId}}/join/f1KnLYiMlDM3jJ7YYrRTl_1Jl2rpLp HTTP/1.1
content-type: application/json

### Join team
# Please update the verification code, the code is generated by `/team/{teamId}/invite`.
# Go to http://localhost:8005 and you'll able to see all the emails sent from the backend.
@teamId = {{profile.response.body.$.teamList[0].id}}
POST http://localhost:4000/team/{{teamId}}/join/f1KnLYiMlDM3jJ7YYrRTl_1Jl2rpLp HTTP/1.1
content-type: application/json

{
  "email": "test3@gmail.com"
}

### Remove user from team
# `8c27d077-fd80-4cda-9b49-b4745d10037d` is the default user in local environment
# The value is from the environment variable named `COGNITO_USER_ID_LOCAL`
@teamId = {{profile.response.body.$.teamList[0].id}}
DELETE http://localhost:4000/team/{{teamId}}/remove/8c27d077-fd80-4cda-9b49-b4745d10037d HTTP/1.1
content-type: application/json

### Edit member
# `8c27d077-fd80-4cda-9b49-b4745d10037d` is the default user in local environment
# The value is from the environment variable named `COGNITO_USER_ID_LOCAL`
@teamId = {{profile.response.body.$.teamList[0].id}}
PUT http://localhost:4000/team/{{teamId}}/edit/8c27d077-fd80-4cda-9b49-b4745d10037d HTTP/1.1
content-type: application/json

{
  "role": "READ_ONLY"
}
